version: '3.8'
services:
  catalogue-api:
    image: edwardwflutter/cms-tech-task-api:latest
    environment:
      SERVER_PORT: 9001
    ports:
      - '9001:9001'

  mongo-service:
    image: mongo:4.4.6
    ports:
      - 27017:27017


  content-managament-service:
    image: content-management-api
    depends_on:
      - mongo-service
      - catalogue-api
    ports:
      - 8080:8080
    environment:
      - MONGODB_HOST=mongo-service
      - SPORTS_API_HOST=http://catalogue-api:9001